(function(){
  function esc(v){return AsUI.escape(v)}
  function chip(v){return '<span class="chip">'+esc(v)+'</span>'}
  function btn(label,action,cls){return '<button class="btn focusable '+(cls||'')+'" onclick="'+action+'">'+esc(label)+'</button>'}
  function safe(fn,fb){try{return fn()}catch(e){return fb!==undefined?fb:{ok:false,error:e.message||String(e)}}}
  function bridge(){return window.AsgardBridge||null}
  function version(){return safe(()=>bridge()&&bridge().getAppVersionInfo?JSON.parse(bridge().getAppVersionInfo()):{versionName:'web-preview',versionCode:-1},{versionName:'unknown',versionCode:-1})}
  function storage(){return safe(()=>bridge()&&bridge().getDeviceStorageInfo?JSON.parse(bridge().getDeviceStorageInfo()):{ok:false,status:'bridge_storage_unavailable'},{ok:false,status:'exception'})}
  function sources(){const rows=safe(()=>AsSources.parse(AsStore.readSources()||''),[]);return {total:rows.length,enabled:rows.filter(x=>x.ok&&x.enabled).length,disabled:rows.filter(x=>x.ok&&!x.enabled).length,invalid:rows.filter(x=>!x.ok).length,types:rows.filter(x=>x.ok).reduce((a,x)=>{a[x.type]=(a[x.type]||0)+1;return a},{})}}
  function parser(){const s=safe(()=>AsStore.parserSettings(),{});return {parserUrl:!!(s.parserUrl||s.jacredBaseUrl),apiKey:!!(s.apiKey||s.jacredApiKey),serviceUrl:!!s.torrServerUrl}}
  function bridgeMethods(){const b=bridge();const m=['openPlayer','openExternalUrl','nativeFetch','getAppVersionInfo','getDeviceStorageInfo','readSourcesTxt','saveSourcesTxt','resetSourcesTxt'];const r={present:!!b,methods:{}};m.forEach(x=>r.methods[x]=!!(b&&b[x]));return r}
  function progress(){return safe(()=>AsStore.progress(),[])}
  function tasks(){return safe(()=>AsStore.torrentTasks(),[])}
  function networkBase(){const online=typeof navigator!=='undefined'?navigator.onLine:null;return {browserOnline:online,nativeFetch:!!(bridge()&&bridge().nativeFetch),testUrl:'https://api.github.com'} }
  function panel(title,status,body){return '<div tabindex="0" class="panel focusable health '+(status||'')+'"><h2>'+esc(title)+'</h2>'+body+'</div>'}
  function collect(){const b=bridgeMethods();const src=sources();const p=parser();const st=storage();const prog=progress();const ts=tasks();const v=version();const net=networkBase();const warnings=[];if(!b.present)warnings.push('Android bridge missing. Running in browser preview or bridge failed.');if(!b.methods.openPlayer)warnings.push('Native player handoff method is unavailable.');if(!b.methods.nativeFetch)warnings.push('nativeFetch unavailable: source requests may hit WebView CORS limits.');if(!src.enabled)warnings.push('No enabled user sources. Search may return only demo or no results.');if(src.invalid)warnings.push('Invalid source rows: '+src.invalid);if(!p.serviceUrl)warnings.push('Configured media service URL is missing. Prepared stream flow may fail.');if(st&&st.freeBytes!==undefined&&Number(st.freeBytes)<200*1024*1024)warnings.push('Low free storage may affect playback/cache.');return {generatedAt:new Date().toISOString(),version:v,network:net,bridge:b,player:{openPlayer:b.methods.openPlayer,progressItems:prog.length,lastProgress:prog[0]||null,tasks:ts.length},cacheStorage:{device:st,local:{sourcesChars:String(AsStore.readSources()||'').length,progressItems:prog.length,tasks:ts.length,favorites:safe(()=>AsStore.favorites(),[]).length,history:safe(()=>AsStore.history(),[]).length}},permissions:{installPackages:'not_checked_in_web_runtime',externalStorage:'not_required_for_assets_webview',network:'INTERNET permission expected in manifest'},sources:src,parserService:p,release:{expectedAsset:'asgard-tv-release.apk',versionName:v.versionName,versionCode:v.versionCode},warnings:warnings}}
  window.AsDiagnosticsV2={last:null,
    collect:collect,
    render(){const r=collect();this.last=r;const cards=[
      panel('Network',''+(r.network.browserOnline===false?'warn':'ok'),'<p>'+chip('browserOnline '+r.network.browserOnline)+chip('nativeFetch '+r.network.nativeFetch)+'</p><p class="muted">nativeFetch is required for WebView-safe source requests.</p>'),
      panel('Player',''+(r.player.openPlayer?'ok':'warn'),'<p>'+chip('openPlayer '+r.player.openPlayer)+chip('progress '+r.player.progressItems)+chip('tasks '+r.player.tasks)+'</p><p class="muted">PlayerActivity handoff depends on openPlayer bridge.</p>'),
      panel('Cache / Storage','ok','<p>'+chip('sources '+r.cacheStorage.local.sourcesChars+' chars')+chip('progress '+r.cacheStorage.local.progressItems)+chip('tasks '+r.cacheStorage.local.tasks)+chip('favorites '+r.cacheStorage.local.favorites)+chip('history '+r.cacheStorage.local.history)+'</p><pre>'+esc(JSON.stringify(r.cacheStorage.device,null,2))+'</pre>'),
      panel('Permissions','ok','<p>'+chip('network '+r.permissions.network)+chip('storage '+r.permissions.externalStorage)+chip('install '+r.permissions.installPackages)+'</p>'),
      panel('Version / Release','ok','<p>'+chip(r.version.versionName||'unknown')+chip('code '+(r.version.versionCode||-1))+chip(r.release.expectedAsset)+'</p>'),
      panel('Source setup',''+((r.sources.enabled&&r.sources.invalid===0)?'ok':'warn'),'<p>'+chip('enabled '+r.sources.enabled)+chip('disabled '+r.sources.disabled)+chip('invalid '+r.sources.invalid)+chip('parser '+r.parserService.parserUrl)+chip('service '+r.parserService.serviceUrl)+'</p><pre>'+esc(JSON.stringify(r.sources.types,null,2))+'</pre>'),
      panel('Warnings',r.warnings.length?'warn':'ok',r.warnings.length?'<ul>'+r.warnings.map(w=>'<li>'+esc(w)+'</li>').join('')+'</ul>':'<p>No static warnings detected.</p>')
    ].join('');AsApp.shell('Diagnostics','Unified troubleshooting: network, player, cache/storage, permissions, version/release, source setup.','<div class="source-toolbar">'+btn('Refresh','AsDiagnosticsV2.render()')+btn('Copy JSON','AsDiagnosticsV2.copy()','secondary')+btn('Source diagnostics','AsSourceDiagnostics.run()','secondary')+btn('Setup wizard','AsSetupWizard.render()','secondary')+'</div><div class="states">'+cards+'</div><div class="panel"><h2>Raw diagnostics JSON</h2><pre>'+esc(JSON.stringify(r,null,2))+'</pre></div><div id="sourceDiagOut"></div>');setTimeout(()=>AsInput&&AsInput.refresh&&AsInput.refresh(),50)},
    copy(){const t=JSON.stringify(this.last||collect(),null,2);if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(t).then(()=>AsApp.toast('Diagnostics copied')).catch(()=>alert(t));}else alert(t)}
  };
  function patch(){if(!window.AsApp||!window.AsUI||!window.AsStore||!window.AsSources){setTimeout(patch,100);return;}AsApp.diagnostics=function(){AsDiagnosticsV2.render()};if(AsUI.state&&AsUI.state.screen==='Диагностика')AsDiagnosticsV2.render();}
  patch();
})();
