(function(){
  const U={groups:[],items:[],detail:null};
  function e(v){return window.AsUI&&AsUI.escape?AsUI.escape(v):String(v||'')}
  function chip(v){return '<span class="chip">'+e(v)+'</span>'}
  function btn(t,a,c){return '<button class="btn focusable '+(c||'')+'" onclick="'+a+'">'+e(t)+'</button>'}
  function target(r){return String(r&&(r.streamUrl||r.magnetUrl||r.torrentUrl||r.url||r.link||'')||'')}
  function kind(r){const u=target(r).toLowerCase();const t=String(r&&(r.kind||r.classification||r.type)||'').toLowerCase();if(t==='playable'||/\.(mp4|m3u8|webm|mkv)(\?|$)/.test(u))return 'stream';if(t==='torrent'||t==='torrent_url'||/\.torrent(\?|$)/.test(u))return 'torrent';if(t==='magnet'||u.startsWith('magnet:?'))return 'magnet';return 'page'}
  function titleOf(r){return String(r&&r.title||r&&r.name||'Unknown').replace(/[\[\(].*?[\]\)]/g,'').replace(/\b(2160p|1080p|720p|480p|web[- ]?dl|bluray|hdrip|x264|x265|hevc|proper|repack)\b/gi,'').replace(/\s+/g,' ').trim()||'Unknown'}
  function score(r){let s=0;const k=kind(r);if(k==='stream')s+=1000;if(k==='torrent')s+=900;if(k==='magnet')s+=850;if(k==='page')s+=100;s+=Number(r.seeders||0)*3;s+=Number(r.peers||0);const q=String(r.quality||r.title||'').toLowerCase();if(q.includes('2160')||q.includes('4k'))s+=80;else if(q.includes('1080'))s+=55;else if(q.includes('720'))s+=20;return s}
  function posterFor(g){const p=(g.options.find(x=>x.posterUrl||x.poster_url)||{}).posterUrl||(g.options.find(x=>x.poster_url)||{}).poster_url||g.poster||'';return p?'<div class="poster poster-img" style="background-image:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.78)),url('+e(p)+')"><span>'+e(g.bestKind||'media')+'</span></div>':'<div class="poster art'+((g.index%6)+1)+'"><span>'+e(g.bestKind||'media')+'</span></div>'}
  function groups(list){const m={};(list||[]).forEach(r=>{const t=titleOf(r);const k=t.toLowerCase();if(!m[k])m[k]={title:t,options:[]};m[k].options.push(r)});return Object.values(m).map((g,i)=>{g.index=i;g.options.sort((a,b)=>score(b)-score(a));g.best=g.options[0];g.bestKind=kind(g.best);g.sources=[...new Set(g.options.map(x=>x.sourceName||x.source||x.parserName||'source'))];return g}).sort((a,b)=>score(b.best)-score(a.best))}
  function topbar(title,subtitle){return '<div class="lampa-topbar"><div class="lampa-title"><h1>'+e(title)+'</h1><p>'+e(subtitle||'')+'</p></div><div class="lampa-tabs"><span class="lampa-tab active">Карточки</span><span class="lampa-tab">Источники</span><span class="lampa-tab">D-pad</span></div></div>'}
  function card(g){return '<article tabindex="0" class="card focusable" onclick="AsLampaUXV15.open('+g.index+')">'+posterFor(g)+'<div class="card-body"><h3>'+e(g.title)+'</h3><p class="muted">'+e(g.options.length+' вариантов · '+g.sources.slice(0,2).join(', '))+'</p>'+chip(g.bestKind)+(g.best.quality?chip(g.best.quality):'')+(g.best.seeders!==undefined?chip('S '+g.best.seeders):'')+'<div class="lampa-card-actions">'+btn('▶ Включить','AsLampaUXV15.playBest('+g.index+')')+btn('Источники','AsLampaUXV15.open('+g.index+')','secondary')+'</div></div></article>'}
  function render(query,report){const raw=report&&report.results||[];const list=window.AsSearchNormalize&&AsSearchNormalize.normalizeList?AsSearchNormalize.normalizeList(raw,query):raw;U.items=list;U.groups=groups(list);if(window.AsMediaSearch)AsMediaSearch.items=list;const errors=(report.reports||[]).filter(x=>!x.ok);if(!U.groups.length)return topbar('Поиск','Результатов нет')+'<div class="lampa-state"><h1>Ничего не найдено</h1><p>Проверь источники/парсер. Ниже диагностика по провайдерам.</p></div><details class="panel"><summary>Diagnostics</summary><pre>'+e(JSON.stringify(report.reports||[],null,2))+'</pre></details>';return topbar('Поиск','Найдено '+U.groups.length+' карточек · '+list.length+' источников')+'<div class="lampa-search-grid">'+U.groups.map(card).join('')+'</div><details class="panel"><summary>Diagnostics · '+errors.length+' errors</summary><pre>'+e(JSON.stringify(report.reports||[],null,2))+'</pre></details>'}
  function srcRow(r,i){const k=kind(r);return '<div tabindex="0" class="lampa-source focusable '+(i===0?'best':'')+'"><div><h3>'+e(r.title||('Источник '+(i+1)))+'</h3><p>'+chip(k)+chip(r.sourceName||r.source||r.parserName||'source')+(r.quality?chip(r.quality):'')+(r.sizeLabel?chip(r.sizeLabel):r.size?chip(String(r.size)):'')+(r.seeders!==undefined?chip('S '+r.seeders):'')+(r.peers!==undefined?chip('P '+r.peers):'')+'</p><p>'+e(target(r))+'</p></div><div>'+btn(i===0?'▶ Лучший':'▶ Включить','AsLampaUXV15.playOption('+i+')')+'</div></div>'}
  function open(idx){const g=U.groups[idx];if(!g)return;U.items=g.options;if(window.AsMediaSearch)AsMediaSearch.items=g.options;U.detail=g;const body='<div class="lampa-shell">'+topbar(g.title,'Выбор источника · '+g.options.length+' вариантов')+'<div class="lampa-detail"><div class="lampa-detail-poster">'+posterFor(g)+'</div><div class="lampa-detail-main"><p class="eyebrow">Asgard · Source selection</p><h1>'+e(g.title)+'</h1><p class="muted">Сначала выбери качество и источник. Если это magnet/torrent, приложение подготовит metadata/files и откроет поток только когда stream URL готов.</p><p>'+chip(g.bestKind)+chip(g.options.length+' вариантов')+chip(g.sources.join(' · '))+'</p><div class="lampa-actions">'+btn('▶ Включить лучший','AsLampaUXV15.playOption(0)')+btn('Назад к поиску','AsUI.nav(\'Поиск\')','secondary')+'</div></div><aside class="lampa-side-panel"><h2>Источники</h2>'+g.options.map(srcRow).join('')+'</aside></div></div>';if(window.AsApp&&AsApp.shell)AsApp.shell(g.title,'Выбор источника',body);if(window.AsInput&&AsInput.refresh)AsInput.refresh()}
  function playBest(idx){const g=U.groups[idx];if(g&&window.AsOneClickPlaybackV5)return AsOneClickPlaybackV5.playResult(g.best)}
  function playOption(i){const r=U.items[i];if(r&&window.AsOneClickPlaybackV5)return AsOneClickPlaybackV5.playResult(r)}
  function patchSearch(){if(!window.AsTitleMediaSearch||!window.AsSources){setTimeout(patchSearch,100);return}AsTitleMediaSearch.search=async function(){const input=document.getElementById('mediaSearchQuery');const q=String(input&&input.value||'').trim();const out=document.getElementById('mediaSearchResults');if(!out)return;if(!q){AsState.setEmpty(out,'Введите название','Например: Interstellar, The Boys, Silo',[]);return}out.innerHTML=topbar('Поиск','Ищу источники')+'<div class="lampa-state"><h1>Ищу...</h1><p>Собираю ответы парсеров, группирую по фильмам и готовлю выбор источников.</p></div>';try{const rep=await AsSources.searchContent(q);out.innerHTML=render(q,rep)}catch(x){AsState.setError(out,'Search failed',x.message||String(x),[{label:'Retry',action:'AsMediaSearch.search()'}])}if(window.AsInput&&AsInput.refresh)AsInput.refresh()};if(window.AsMediaSearch)AsMediaSearch.search=function(){return AsTitleMediaSearch.search()}}
  function patchHomeDetails(){if(!window.AsHomeTMDBV14){setTimeout(patchHomeDetails,150);return}const old=AsHomeTMDBV14.details;AsHomeTMDBV14.details=async function(id){await old(id);setTimeout(()=>{document.querySelectorAll('.source-row').forEach(x=>x.classList.add('lampa-season'))},60)} }
  window.AsLampaUXV15={render,open,playBest,playOption,groups:U.groups,items:U.items};
  patchSearch();patchHomeDetails();
})();
