(function(){
  function esc(v){return AsUI.escape(v)}
  function chip(v){return '<span class="chip">'+esc(v)+'</span>'}
  function btn(label,action,cls){return '<button class="btn focusable '+(cls||'')+'" onclick="'+action+'">'+esc(label)+'</button>'}
  function sizeLabel(v){const n=Number(v||0);if(!n)return '';if(n>=1073741824)return (n/1073741824).toFixed(2)+' GB';if(n>=1048576)return (n/1048576).toFixed(1)+' MB';return n+' B'}
  function q(){return ((document.getElementById('mediaSearchQuery')||{}).value||'').trim()}
  function isTorrentLike(r){return r&&(['torrent','magnet'].includes(r.classification)||r.magnetUrl||r.torrentUrl||/^magnet:\?/i.test(r.url||''))}
  function isPlayable(r){return r&&r.classification==='playable'&&r.url}
  function sourceKind(r){if(isPlayable(r))return 'playable';if(isTorrentLike(r))return r.magnetUrl||/^magnet:\?/i.test(r.url||'')?'magnet':'torrent';if(r&&r.url)return 'link';return 'unknown'}
  function mediaTitle(r,query){return r.title||r.name||query||'Media result'}
  function qualityFromText(r){const s=String((r.title||'')+' '+(r.description||'')+' '+(r.quality||'')).toUpperCase();if(s.includes('2160')||s.includes('4K'))return '4K';if(s.includes('1080'))return '1080p';if(s.includes('720'))return '720p';if(s.includes('480'))return '480p';return r.quality||''}
  function normalized(r,i,query){const kind=sourceKind(r);return Object.assign({},r,{mediaId:'media_'+i,title:mediaTitle(r,query),kind,quality:qualityFromText(r),sourceName:r.sourceName||r.source||r.parserName||'User source',rightsStatus:r.rightsStatus||'User Source / Unknown Rights',requiresUserConfirmation:kind==='torrent'||kind==='magnet',score:Number(r.rank||0)+(kind==='playable'?100:kind==='torrent'||kind==='magnet'?70:20)+(Number(r.seeders||0)>0?Math.min(20,Math.log2(Number(r.seeders)+1)*3):0)});}
  function sortMedia(a,b){return (b.score-a.score)||(Number(b.seeders||0)-Number(a.seeders||0))||String(a.title).localeCompare(String(b.title))}
  function unique(list){const seen={};return list.filter(r=>{const k=String(r.magnetUrl||r.torrentUrl||r.url||r.title).toLowerCase();if(!k||seen[k])return false;seen[k]=true;return true;});}
  function normalizeReport(report,query){const results=unique((report.results||[]).map((r,i)=>normalized(r,i,query))).sort(sortMedia);const groups={playable:[],torrent:[],magnet:[],link:[],unknown:[]};results.forEach(r=>(groups[r.kind]||groups.unknown).push(r));return {query,results,groups,reports:report.reports||[],summary:{total:results.length,playable:groups.playable.length,torrent:groups.torrent.length,magnet:groups.magnet.length,link:groups.link.length,errors:(report.reports||[]).filter(x=>!x.ok).length,sourceCount:report.sourceCount||0,reportsOk:report.reportsOk||0}}}
  function resultActions(r,i){let actions='';if(isPlayable(r))actions+=btn('▶ Смотреть','AsMediaSearch.play('+i+')');if(isTorrentLike(r))actions+=btn('Create media task','AsMediaSearch.createTask('+i+')')+btn('TorrServer → ExoPlayer','AsMediaSearch.playViaService('+i+')','secondary');if(r.url&&!isPlayable(r)&&!isTorrentLike(r))actions+=btn('Open link','AsMediaSearch.open('+i+')','secondary');return actions+btn('Diagnostics','AsMediaSearch.diag('+i+')','secondary')}
  function resultCard(r,i){return '<div tabindex="0" class="source-row focusable"><h3>'+esc(r.title)+'</h3><p>'+chip(r.kind)+chip(r.sourceName)+chip(r.rightsStatus)+(r.quality?chip(r.quality):'')+(r.size?chip(sizeLabel(r.size)):'')+(r.seeders!==undefined?chip('S '+r.seeders):'')+(r.peers!==undefined?chip('P '+r.peers):'')+(r.score?chip('score '+Math.round(r.score)):'')+'</p><p class="muted">'+esc(r.description||r.url||r.magnetUrl||r.torrentUrl||'')+'</p><p class="muted">'+esc(r.magnetUrl||r.torrentUrl||r.url||'')+'</p><div class="source-actions">'+resultActions(r,i)+'</div></div>'}
  function groupSection(title,items,all){if(!items.length)return '';return '<section class="shelf"><div class="shelf-head"><h2>'+esc(title)+'</h2><span>'+items.length+'</span></div>'+items.map(x=>resultCard(x,all.indexOf(x))).join('')+'</section>'}
  window.AsMediaSearch={last:null,items:[],
    render(){const srcs=AsSources.parse(AsStore.readSources()||'').filter(s=>s.ok&&s.enabled);AsApp.shell('Media Search','Main product path: search movie title → user-configured parser/source → media/torrent result → playable task / ExoPlayer.','<div class="warn"><b>Legal-safe mode:</b> Asgard TV uses only user-configured sources/parsers and public demo links. No bundled prohibited catalogs, no bypasses.</div><div class="search-box"><input class="focusable" id="mediaSearchQuery" placeholder="Movie title / series title / query"><button class="btn focusable" onclick="AsMediaSearch.search()">Search media</button><button class="btn secondary focusable" onclick="AsUI.nav(\'Источники\')">Sources</button><button class="btn secondary focusable" onclick="AsParserSettings.render()">Parser & service</button></div><div class="panel"><h2>Configured search inputs</h2><p>'+chip('enabled sources '+srcs.length)+chip('user-controlled')+chip('no bundled catalogs')+'</p><p class="muted">For torrent/media results, configure your own parser/source in Sources or Parser & TorrServer settings.</p></div><div id="mediaSearchResults">'+AsState.empty('Введите название','Например: Big Buck Bunny или название фильма из вашего user-configured parser.',[])+'</div>');setTimeout(()=>AsInput&&AsInput.refresh(),50)},
    async search(){const query=q();const out=document.getElementById('mediaSearchResults');if(!out)return;if(!query){AsState.setEmpty(out,'Пустой запрос','Введите название фильма или сериала.',[]);return;}AsState.setLoading(out,'Ищу media results','Проверяю enabled user sources и configured parsers.');let report;try{report=await AsSources.searchContent(query)}catch(e){AsState.setError(out,'Media search failed',e.message||String(e),[{label:'Retry',action:'AsMediaSearch.search()'},{label:'Sources',action:"AsUI.nav('Источники')"}]);return;}const nr=normalizeReport(report,query);this.last=nr;this.items=nr.results;const s=nr.summary;const errors=(nr.reports||[]).filter(x=>!x.ok).map(x=>({source:x.source,type:x.type,status:x.status,error:x.error}));if(!nr.results.length){AsState.setEmpty(out,'Нет media результатов','Проверьте enabled sources, parser URL/API key или измените запрос.',[{label:'Sources',action:"AsUI.nav('Источники')"},{label:'Parser & service',action:'AsParserSettings.render()'},{label:'Retry',action:'AsMediaSearch.search()'}]);return;}out.innerHTML='<div class="panel"><h2>Media search summary</h2><p>'+chip('total '+s.total)+chip('playable '+s.playable)+chip('torrent '+s.torrent)+chip('magnet '+s.magnet)+chip('link '+s.link)+chip('errors '+s.errors)+chip('sources '+s.sourceCount)+'</p>'+(errors.length?'<pre>'+esc(JSON.stringify(errors,null,2))+'</pre>':'')+'</div>'+groupSection('Direct playable',nr.groups.playable,nr.results)+groupSection('Torrent files',nr.groups.torrent,nr.results)+groupSection('Magnet links',nr.groups.magnet,nr.results)+groupSection('Other links',nr.groups.link,nr.results);AsInput&&AsInput.refresh()},
    play(i){const r=this.items[i];if(!r||!r.url)return;if(window.AsgardBridge&&AsgardBridge.openPlayer)AsgardBridge.openPlayer(r.url,r.title,0);else window.open(r.url,'_blank')},
    createTask(i){const r=this.items[i];if(!r)return;const ok=!r.requiresUserConfirmation||confirm('I confirm I have rights to access this content.');if(!ok)return;const target=r.magnetUrl||r.torrentUrl||r.url;const type=r.magnetUrl||/^magnet:\?/i.test(target)?'magnet':'torrent_url';if(window.AsTorrent&&AsTorrent.addTask){const task=AsTorrent.addTask({type,url:target,title:r.title,sourceName:r.sourceName,quality:r.quality,size:r.size,seeders:r.seeders,peers:r.peers,rightsConfirmed:true,createdFrom:'media_search'});alert(JSON.stringify({ok:true,status:'media_task_created',task},null,2));return;}alert(JSON.stringify({ok:false,status:'torrent_task_api_unavailable'},null,2))},
    async playViaService(i){const r=this.items[i];if(!r)return;const ok=!r.requiresUserConfirmation||confirm('I confirm I have rights to access this content.');if(!ok)return;const out=document.getElementById('mediaSearchResults');if(out)out.insertAdjacentHTML('afterbegin',AsState.loading('Preparing playable stream','Sending selected result to configured service.'));const res=await AsTorrServerAdapter.preparePlayableFromResult(r);if(res.ok&&res.streamUrl){if(window.AsgardBridge&&AsgardBridge.openPlayer)AsgardBridge.openPlayer(res.streamUrl,r.title,0);else window.open(res.streamUrl,'_blank');return;}alert(JSON.stringify(res,null,2))},
    open(i){const r=this.items[i];if(!r||!r.url)return;if(window.AsgardBridge&&AsgardBridge.openExternalUrl)AsgardBridge.openExternalUrl(r.url);else window.open(r.url,'_blank')},
    diag(i){const r=this.items[i];if(!r)return;alert(JSON.stringify({title:r.title,kind:r.kind,sourceName:r.sourceName,quality:r.quality,size:r.size,seeders:r.seeders,peers:r.peers,classification:r.classification,rightsStatus:r.rightsStatus,requiresUserConfirmation:r.requiresUserConfirmation,url:r.url||'',magnetUrl:r.magnetUrl?'present':'missing',torrentUrl:r.torrentUrl||''},null,2))}
  };
  function patch(){if(!window.AsApp||!window.AsSources||!window.AsStore||!window.AsUI||!window.AsState){setTimeout(patch,100);return;}AsApp.search=function(){AsMediaSearch.render()};const oldDetails=AsApp.details&&AsApp.details.bind(AsApp);if(oldDetails&&!AsApp.__mediaSearchDetailsPatched){AsApp.__mediaSearchDetailsPatched=true;AsApp.details=function(id){oldDetails(id);setTimeout(()=>{const p=document.querySelector('.detail-actions');const title=document.querySelector('.premium-detail h2,.detail h2');if(p&&!document.getElementById('findMediaBtn'))p.insertAdjacentHTML('beforeend',btn('Find media sources','AsUI.nav(\'Поиск\');setTimeout(()=>{const q=document.getElementById(\'mediaSearchQuery\');if(q){q.value=\''+esc((title&&title.textContent)||'')+'\';AsMediaSearch.search();}},100)','secondary').replace('<button','<button id="findMediaBtn"'));AsInput&&AsInput.refresh();},80)}}if(AsUI.state.screen==='Поиск')AsMediaSearch.render()}
  patch();
})();
