(function(){
  function safeJson(text,fallback){try{return JSON.parse(text)}catch(e){return fallback}}
  function norm(url){return String(url||'').trim().replace(/\/+$/,'')}
  function isPlaceholder(url){return /^USER_CONFIGURED_/i.test(String(url||''))}
  function sortParsers(list){return (list||[]).filter(p=>p&&p.enabled!==false&&p.url&&!isPlaceholder(p.url)).sort((a,b)=>Number(a.priority||99)-Number(b.priority||99))}
  window.AsParserManager={
    async loadBundledParsers(){const b=window.AsgardBridge;const text=b&&b.readAsset?b.readAsset('parsers.json'):'';return safeJson(text,{parsers:[],defaultParserType:'jacred',remoteConfigEnabled:false,remoteConfigUrl:'',defaultTorrServerUrl:''})},
    async ensureDefaults(){const cfg=await this.loadBundledParsers();const s=AsStore.settings();const parser=Object.assign({},AsStore.parserSettings());let changed=false;if(!parser.torrServerUrl&&cfg.defaultTorrServerUrl){parser.torrServerUrl=cfg.defaultTorrServerUrl;changed=true}if(changed)AsStore.saveParserSettings(parser);return parser},
    async loadRemoteParsers(){const cfg=await this.loadBundledParsers();if(!cfg.remoteConfigEnabled||!cfg.remoteConfigUrl)return {parsers:[]};try{const r=await fetch(cfg.remoteConfigUrl,{headers:{Accept:'application/json'}});if(!r.ok)return {parsers:[]};return safeJson(await r.text(),{parsers:[]})}catch(e){return {parsers:[],error:e.message}}},
    getUserParsers(){const s=AsStore.parserSettings();const list=[];if(s.jacredBaseUrl&&!isPlaceholder(s.jacredBaseUrl))list.push({name:'User JacRed',type:'jacred',url:s.jacredBaseUrl,apiKey:s.jacredApiKey||'',apiKeyRequired:false,priority:0,enabled:true,notes:'user saved parser'});return list},
    mergeParsers(bundled,remote,userSaved){const byKey={};[...(bundled&&bundled.parsers||[]),...(remote&&remote.parsers||[]),...(userSaved||[])].forEach(p=>{if(!p||!p.url||isPlaceholder(p.url))return;const key=(p.type||'jacred')+'|'+norm(p.url);byKey[key]=Object.assign({},byKey[key]||{},p,{url:norm(p.url)})});return sortParsers(Object.values(byKey))},
    normalizeBaseUrl(url){return norm(url)},
    buildSearchUrls(parser,query){const base=norm(parser.url);const apiKey=parser.apiKey||'';const endpoint=base.endsWith('/api/v2.0/indexers/all/results/torznab/api')?base:base+'/api/v2.0/indexers/all/results/torznab/api';const mk=(withKey,cat)=>{const u=new URL(endpoint);if(withKey&&apiKey)u.searchParams.set('apikey',apiKey);u.searchParams.set('t','search');if(cat)u.searchParams.set('cat','');u.searchParams.set('q',query||'test');return u.toString()};return [mk(false,false),mk(true,false),mk(true,true)]},
    async testParser(parser){const started=Date.now();try{if(!parser||!parser.url||isPlaceholder(parser.url))return {name:parser&&parser.name,url:parser&&parser.url,ok:false,status:'missing_url',elapsedMs:0,lastError:'Parser URL is empty or placeholder'};const settings={jacredBaseUrl:parser.url,jacredApiKey:parser.apiKey||''};const d=await AsJacRedAdapter.discover(settings);return {name:parser.name,url:parser.url,ok:!!d.ok,status:d.status,httpStatus:d.httpStatus||0,responseType:d.kind||'',endpointUsed:d.endpoint||d.detectedUrl||'',elapsedMs:d.elapsedMs||Date.now()-started,lastError:d.error||''}}catch(e){return {name:parser&&parser.name,url:parser&&parser.url,ok:false,status:e.name==='AbortError'?'timeout':'failed',httpStatus:0,responseType:'',endpointUsed:'',elapsedMs:Date.now()-started,lastError:e.message||String(e)}}},
    async testAllParsers(){await this.ensureDefaults();const bundled=await this.loadBundledParsers();const remote=await this.loadRemoteParsers();const parsers=this.mergeParsers(bundled,remote,this.getUserParsers());const reports=[];for(const p of parsers){reports.push(await this.testParser(p))}return {parsers,reports,defaultTorrServerUrl:bundled.defaultTorrServerUrl||''}},
    async selectBestParser(){await this.ensureDefaults();const current=this.getActiveParser();if(current&&!isPlaceholder(current.url)){const t=await this.testParser(current);if(t.ok)return current}const all=await this.testAllParsers();for(let i=0;i<all.parsers.length;i++){if(all.reports[i]&&all.reports[i].ok){this.saveActiveParser(all.parsers[i]);return all.parsers[i]}}if(all.parsers.length){this.saveActiveParser(all.parsers[0]);return all.parsers[0]}return null},
    getActiveParser(){const p=AsStore.settings().activeParser||null;return p&&p.url&&!isPlaceholder(p.url)?p:null},
    saveActiveParser(parser){const s=AsStore.settings();s.activeParser=parser;AsStore.saveSettings(s);const ps=AsStore.parserSettings();if(parser&&parser.url&&!ps.jacredBaseUrl)AsStore.saveParserSettings(Object.assign({},ps,{jacredBaseUrl:parser.url,jacredApiKey:parser.apiKey||ps.jacredApiKey||''}));return true},
    async fallbackToNextParser(currentParser){const all=await this.testAllParsers();const parsers=all.parsers;const curKey=(currentParser&&currentParser.url)||'';let start=parsers.findIndex(p=>p.url===curKey);if(start<0)start=0;for(let i=1;i<=parsers.length;i++){const idx=(start+i)%parsers.length;const p=parsers[idx];const r=await this.testParser(p);if(r.ok){this.saveActiveParser(p);return p}}return null}
  };
})();
