window.AsUpdates={
  repo:'asker421/Asgard',
  api:'https://api.github.com/repos/asker421/Asgard/releases/latest',
  state:'idle',
  last:null,
  current(){const b=window.AsgardBridge;if(b&&b.getAppVersionInfo){try{return JSON.parse(b.getAppVersionInfo())}catch(e){return{versionName:'unknown',versionCode:0,repo:this.repo,error:e.message}}}return{versionName:'unknown',versionCode:0,repo:this.repo}},
  semver(v){return String(v||'0.0.0').replace(/^v/i,'').split('.').map(x=>Number(String(x).replace(/[^0-9].*$/,''))||0)},
  compareSemver(a,b){const x=this.semver(a),y=this.semver(b);for(let i=0;i<3;i++){if(x[i]>y[i])return 1;if(x[i]<y[i])return -1}return 0},
  parseBodyMeta(body){const text=String(body||'');const jsonBlock=text.match(/\{[\s\S]*?"versionCode"[\s\S]*?\}/);if(jsonBlock){try{return JSON.parse(jsonBlock[0])}catch(e){}}const code=(text.match(/versionCode\s*[:=]?\s*(\d+)/i)||[])[1];const name=(text.match(/versionName\s*[:=]?\s*"?([0-9]+\.[0-9]+\.[0-9]+)"?/i)||[])[1];return{versionCode:code?Number(code):0,versionName:name||''}},
  apkAsset(assets){return (assets||[]).find(a=>String(a.name||'').toLowerCase().endsWith('.apk'))||null},
  safeAsset(asset){if(!asset||!asset.url)return false;const u=String(asset.url);return u.startsWith('https://github.com/')||u.startsWith('https://objects.githubusercontent.com/')},
  async check(){const cur=this.current();const result={current:cur,ok:false,state:'checking',message:'',release:null,updateAvailable:false,apk:null};try{const r=await fetch(this.api,{headers:{'Accept':'application/vnd.github+json'}});if(!r.ok)throw new Error(r.status===403?'GitHub API rate limit or access denied':'GitHub status '+r.status);const data=await r.json();const assets=(data.assets||[]).map(a=>({name:a.name,url:a.browser_download_url,size:a.size,downloadCount:a.download_count||0}));const meta=this.parseBodyMeta(data.body||'');const apk=this.apkAsset(assets);const latestName=meta.versionName||String(data.tag_name||'').replace(/^v/i,'')||'';const latestCode=Number(meta.versionCode||0);let update=false;if(latestCode>0&&Number(cur.versionCode||0)>0)update=latestCode>Number(cur.versionCode);else if(latestName&&cur.versionName&&cur.versionName!=='unknown')update=this.compareSemver(latestName,cur.versionName)>0;result.ok=true;result.state=update?'update_available':'up_to_date';result.updateAvailable=update;result.apk=apk;result.release={tag:data.tag_name||'',name:data.name||'',versionName:latestName,versionCode:latestCode,body:data.body||'',url:data.html_url||'',assets,apkAsset:apk};result.message=update?'New version available':'You are up to date';this.last=result;return result}catch(e){result.ok=false;result.state='error';result.message='Update check failed: '+e.message;this.last=result;return result}},
  open(url){const b=window.AsgardBridge;if(b&&b.openExternalUrl)return b.openExternalUrl(url);window.open(url,'_blank');return true},
  download(){const r=this.last;if(!r||!r.apk)return{ok:false,error:'No APK asset found'};if(!this.safeAsset(r.apk))return{ok:false,error:'APK URL is not from GitHub Releases'};const b=window.AsgardBridge;if(b&&b.downloadAndInstallApk)return b.downloadAndInstallApk(r.apk.url);this.open(r.apk.url);return{ok:true,status:'opened_apk_url'}},
  onDownloadProgress(percent){this.state='downloading';const el=document.getElementById('updateOut');if(el)el.textContent='Downloading update: '+percent+'%'}
};
